theme = "hugo-sugoi"
baseURL = ""
languageCode = "he"
direction = "rtl"
title = "מרכז הדרכה"
summaryLength = 20
paginate = 5
# Google Analytics ID, Uncomment below line to enable
# googleAnalytics = "UA-123-45"

# Enter your disqus Shortname and uncomment below line to enable
# disqusShortname = "yourdiscussshortname"

[params]
favicon = "images/favicon.png"
herotitle = "מרכז הדרכה גנרי"
herolink = "https://github.com/aanupam23/hugo-sugoi"
herolinktext = "Check Now"
contact = "Send me a message and I will get back as soon as possible."
js = "js/main.js"


[hero]

[menu]
    [[menu.nav]]
        name    = "search"
        pre = "<i class='fas fa-search'></i>"
        url     = "search"
        weight  = -1
    [[menu.nav]]
        name    = "about"
        pre = "<i class='fas fa-home'></i>"
        url     = "about"
        weight  = -2
    [[menu.nav]]
        name    = "blog"
        pre = "<i class='fas fa-list'></i>"
        url     = "post"
        weight  = -3
    [[menu.nav]]
        name    = "contact"
        pre = "<i class='fas fa-envelope'></i>"
        url     = "contact"
        weight  = -4
